@startuml gameState

state "Title" as t
state "Playing" as p
state "Result" as re
state "Setting" as s
state "Ranking" as ra

[*] -d-> t
t -r-> p : Press Enter
p -[hidden]d-> ra
s -[hidden]r-> ra
t -> ra : Press R
ra -u-> t : Press BS
t -d-> s : Press S
s -u-> t : Press BS
p -r-> re : Gameover
re -l-> t : Press BS
re -l-> p : Press R

@enduml

@startuml Game Move State

state "LEFT" as l
state "RIGHT" as r
state "UP" as u
state "DOWN" as d

[*] -d-> l
l -d-> u : Up
l -r-> r : Right
u -r-> d : Down
r -d-> d : Down

l -> d : Down

r -> u : Up
r -l-> l : Left

u -u-> l : Left
u -> r : Right

d -l-> u : Up
d -> l : Left
d -u-> r : Right

@enduml