@startuml gameState

state "Title" as title
state "Playing" as play
state "Result" as result
state "Setting" as setting
state "Ranking" as rank

[*] -d-> title
title -r-> play : Press Enter
play -[hidden]d-> rank
setting -[hidden]r-> rank
title -> rank : Press R
rank -u-> title : Press BS
title -d-> setting : Press S
setting -u-> title : Press BS
play -r-> result : Gameover
result -l-> title : Press BS
result -l-> play : Press R


@enduml